const ActionForQuestion = {
    START_TEST: "START_TEST",
    SELECT_ANSWER: "SELECT_ANSWER",
    DELETE_SELECT_ANSWER: "DELETE_SELECT_ANSWER",
    GO_TO_NEXT_QUESTION: "GO_TO_NEXT_QUESTION",
    SHOW_TEST_RESULT: "SHOW_TEST_RESULT",
    SHOW_CORRECT_ANSWER: "SHOW_CORRECT_ANSWER",
    SHOW_WRONG_ANSWER: "SHOW_WRONG_ANSWER"
}

export default ActionForQuestion;